### PR TITLE
table as its own schema object

### PR DESCRIPTION
**Pull request by roffelsaurus**
This solves #1 so we can use this plugin in graphql and by extension, Gatsby(which is my use case).

This is backwards compatible with the in-line schema and also GraphQl deployable.

I tested this change to be backwards compatible in Sanity UI and having same groq result in sanity Vision.

I also tested sanity graphql deploy,
and the following queries work fine in sanity playground and gatsby iQL.

```
{
  allConfigs {
    translations {
      rows {
        cells
      }
    }
  }
}
```

```
{
  sanityConfig(_id: {eq: "global-config"}) {
    translations {
      rows {
        cells
      }
    }
  }
}
```

### CODE REVIEW

**Comment by rhythmhq** [comment]
Hi @roffelsaurus @rdunk Can we get this merged please?

**Comment by roffelsaurus** [comment]
@rhythmhq  Unfortunately it seems like the maintainer has disappeared. As a workaround you can follow the steps I outline in #1 to just get the fix as a local plugin(this is what I still have as a solution as I don't like to put up a duplicate on npm of my fork)

Another and probably better option is to use the other similar package: https://github.com/fredjens/sanity-datatable

That seems to have gotten pretty much the same pull request as this merged in already.

**Comment by rhythmhq** [comment]
Hi @roffelsaurus thanks for the reply
I have done the above already actually, and I spoke briefly to @rdunk and he was planning to review the PR after his holiday.

Sanity-datatable somewhat bafflingly doesn't have the ability to delete rows and columns, so that one is out.

Thanks for the response, I'm all up and running. Cheers!

**Comment by rdunk** [comment]
Hi @roffelsaurus @rhythmhq. Can only apologise for not getting round to this, is the PR still relevant or has this package been superseded by something else now? I've mostly stepped away from using Sanity so I'm not sure what recent developments have been.

**Comment by lanelps** [comment]
Hi @rdunk , I've only just come into this as I was needing a table schema for a project I'm working on. I definitely couldn't find anything else out there apart from the sanity datatable plugin which still has its issues as well.

I would definitely say that this PR is still relevant!

**Comment by roffelsaurus** [comment]
yes, my org still use it, but as a local plugin because this PR was needed.
We can take over maintenance if you are fine with that.

søn. 26. apr. 2020 kl. 12:35 skrev Lane Le Prevost-Smith <
notifications@github.com>:

**Comment by Slooowpoke** [comment]
Could this be re-looked at? I'm currently using a monkey-patch for it but I imagine it would be nice to have this project maintained if Sanity has an update.

**Comment by roffelsaurus** [comment]
The maintainer seems to have gone AWAL, so I did an off-site fork to take over maintenance and changed the plugin to be "bring-your-own" schema: https://github.com/ssfbank/sanity-plugin-byo-table

**Pull request closed without merging**
